### PR TITLE
Fixed Sonar code smells

### LINKED ISSUE #61: Fix Sonar code smells

### PR DESCRIPTION
**Pull request by lorenzobucci**
Closes #61

### CODE REVIEW

**Review by marcodiri — APPROVED** [review]

File: java_socketio_chatroom_client/src/main/java/io/github/marcodiri/java_socketio_chatroom_client/view/swing/ClientSwingView.java [hunk 1]
```diff
@@ -188,12 +189,19 @@ public void keyReleased(KeyEvent e) {
...
                 if (!txtMessage.getText().trim().isEmpty() && e.getKeyCode() == KeyEvent.VK_ENTER) {
+                    txtErrorMessage.setText("");
                     ClientMessage msg = new ClientMessage(
                             new Timestamp(System.currentTimeMillis()),
                             txtUsername.getText(),
                             txtMessage.getText()
                     );
-                    client.sendMessage(msg);
+                    try {
+                        client.sendMessage(msg);
```
Comment (marcodiri) [inline java_socketio_chatroom_client/src/main/java/io/github/marcodiri/java_socketio_chatroom_client/view/swing/ClientSwingView.java]: Can we move `txtMessage.setText("");` here and remove `return` from the `catch`?
```suggestion
                        client.sendMessage(msg);
                        txtMessage.setText("");
```

File: java_socketio_chatroom_client/src/main/java/io/github/marcodiri/java_socketio_chatroom_client/view/swing/ClientSwingView.java [hunk 2]
```diff
@@ -188,12 +189,19 @@ public void keyReleased(KeyEvent e) {
...
+                    } catch (SocketException ex) {
+                        LOGGER.error(ex.getMessage());
+                        txtErrorMessage.setText(ex.getMessage());
```
Comment (marcodiri) [inline java_socketio_chatroom_client/src/main/java/io/github/marcodiri/java_socketio_chatroom_client/view/swing/ClientSwingView.java]: May be better to call showError

File: java_socketio_chatroom_client/src/main/java/io/github/marcodiri/java_socketio_chatroom_client/view/swing/ClientSwingView.java [hunk 3]
```diff
@@ -188,12 +189,19 @@ public void keyReleased(KeyEvent e) {
             @Override
             public void keyPressed(KeyEvent e) {
                 if (!txtMessage.getText().trim().isEmpty() && e.getKeyCode() == KeyEvent.VK_ENTER) {
+                    txtErrorMessage.setText("");
```
Comment (marcodiri) [inline java_socketio_chatroom_client/src/main/java/io/github/marcodiri/java_socketio_chatroom_client/view/swing/ClientSwingView.java]: Add a test to justify this line

File: java_socketio_chatroom_client/src/main/java/io/github/marcodiri/java_socketio_chatroom_client/view/swing/ClientSwingView.java (hunk 2 above)
Comment (lorenzobucci) [reply java_socketio_chatroom_client/src/main/java/io/github/marcodiri/java_socketio_chatroom_client/view/swing/ClientSwingView.java]: showError needs a state to restore in case an error occurs. Here there is no state to restore...

File: java_socketio_chatroom_client/src/main/java/io/github/marcodiri/java_socketio_chatroom_client/view/swing/ClientSwingView.java (hunk 1 above)
Comment (lorenzobucci) [reply java_socketio_chatroom_client/src/main/java/io/github/marcodiri/java_socketio_chatroom_client/view/swing/ClientSwingView.java]: You are right
