### PR TITLE
Fixed ServerWrapper survived mutants

### LINKED ISSUE #13: Fixing ServerWrapper survived mutations

### PR DESCRIPTION
**Pull request by lorenzobucci**
Closes #13

### CODE REVIEW

File: java_socketio_chatroom_server/src/test/java/io/github/marcodiri/java_socketio_chatroom_server/ServerWrapperTest.java [hunk 1]
```diff
@@ -14,6 +21,15 @@ public void setup() {
         serverWrapper = new ServerWrapper();
     }
 
+    @After
+    public void alwaysStopServer() {
+        try {
+            serverWrapper.stopServer();
+        } catch (Exception ignored) {
+
```
Comment (marcodiri) [inline java_socketio_chatroom_server/src/test/java/io/github/marcodiri/java_socketio_chatroom_server/ServerWrapperTest.java]: maybe call `fail()` on exception?

Comment (lorenzobucci) [reply java_socketio_chatroom_server/src/test/java/io/github/marcodiri/java_socketio_chatroom_server/ServerWrapperTest.java]: yes, good idea. if it enters the catch block the tests will fail and the exception will still be ignored because it is not thrown by our methods

**Review by marcodiri — APPROVED** [review]
